/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/case": {
    /** Create Case */
    post: operations["create_case_api_case_post"];
  };
  "/api/case/voice": {
    /**
     * Create Voice Case
     * @description Create a case for voice-only transcription (no image)
     */
    post: operations["create_voice_case_api_case_voice_post"];
  };
  "/api/case/{case_id}/finalize": {
    /**
     * Finalize Case
     * @description Deep advisory report over the full conversation once a live case ends.
     */
    post: operations["finalize_case_api_case__case_id__finalize_post"];
  };
  "/api/case/{case_id}/transcribe": {
    /** Transcribe Step */
    post: operations["transcribe_step_api_case__case_id__transcribe_post"];
  };
  "/auth/login": {
    /**
     * Auth Login
     * @description Exchange credentials for a bearer token (required in clinical mode).
     */
    post: operations["auth_login_auth_login_post"];
  };
  "/auth/ws-ticket": {
    /**
     * Auth Ws Ticket
     * @description Mint a short-lived WS-scoped ticket for the authenticated session.
     * WebSocket URLs carry this instead of the session JWT so proxy access
     * logs never see a long-lived credential.
     */
    post: operations["auth_ws_ticket_auth_ws_ticket_post"];
  };
  "/ehr/export_clinical_summary": {
    /**
     * Export Clinical Summary
     * @description Export clinical summary back to EHR system (mockup for Epic/Cerner integration)
     */
    post: operations["export_clinical_summary_ehr_export_clinical_summary_post"];
  };
  "/ehr/import_patient_data": {
    /**
     * Import Patient Data
     * @description Import patient data from EHR system (mockup for Epic/Cerner integration)
     */
    post: operations["import_patient_data_ehr_import_patient_data_post"];
  };
  "/ehr/patients": {
    /**
     * List Ehr Patients
     * @description List all available EHR patients
     */
    get: operations["list_ehr_patients_ehr_patients_get"];
  };
  "/ehr/patients/{patient_id}": {
    /**
     * Get Ehr Patient
     * @description Get specific EHR patient data
     */
    get: operations["get_ehr_patient_ehr_patients__patient_id__get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/image_infer": {
    /**
     * Image Infer
     * @description Image-only flow, returns image findings.
     */
    post: operations["image_infer_image_infer_post"];
  };
  "/infer": {
    /**
     * Infer
     * @description Conversation-only flow (no image).
     */
    post: operations["infer_infer_post"];
  };
  "/infer_from_image_only": {
    /**
     * Infer From Image Only
     * @description Image-only flow that tries to bind EHR:
     * 1) match by filename → EHR
     * 2) else match by top predicted label → first EHR with same chexpert_label
     */
    post: operations["infer_from_image_only_infer_from_image_only_post"];
  };
  "/knowledge_base/mode": {
    /**
     * Get Knowledge Base Mode
     * @description Facts about the loaded knowledge base.
     */
    get: operations["get_knowledge_base_mode_knowledge_base_mode_get"];
    /**
     * Set Knowledge Base Mode
     * @description Kept for API compatibility: there is a single local store, so the
     * requested mode is echoed but the facts are the same.
     */
    post: operations["set_knowledge_base_mode_knowledge_base_mode_post"];
  };
  "/metrics": {
    /** Metrics Endpoint */
    get: operations["metrics_endpoint_metrics_get"];
  };
  "/multimodal_infer": {
    /**
     * Multimodal Infer
     * @description Full flow:
     * - Conversation (payload.utterances)
     * - Optional patient_id hint
     * - Optional image upload
     * - Fuse image + text + EHR
     * - RAG advisory + live questions when low confidence
     */
    post: operations["multimodal_infer_multimodal_infer_post"];
  };
  "/multimodal_voice_infer": {
    /**
     * Multimodal Voice Infer
     * @description Full multimodal inference with voice + image:
     * - Transcribe audio conversation
     * - Analyze uploaded image (optional)
     * - Fuse voice + image + EHR
     * - RAG advisory + live questions when low confidence
     */
    post: operations["multimodal_voice_infer_multimodal_voice_infer_post"];
  };
  "/quick_analysis": {
    /**
     * Quick Analysis
     * @description Return only potential issues with scores (top-k fused candidates).
     * Accepts optional utterances + optional image; fuses and returns a compact list.
     */
    post: operations["quick_analysis_quick_analysis_post"];
  };
  "/reload_ehr": {
    /**
     * Reload Ehr
     * @description Reload EHR JSON without restarting the server (optional convenience).
     */
    post: operations["reload_ehr_reload_ehr_post"];
  };
  "/reload_retriever": {
    /**
     * Reload Retriever
     * @description Re-initialize the RAG store after a KB rebuild (init is otherwise
     * once-per-process). Re-warms on a background thread.
     */
    post: operations["reload_retriever_reload_retriever_post"];
  };
  "/structured_diagnosis": {
    /**
     * Structured Diagnosis
     * @description Enhanced structured differential diagnosis with risk factors, red flags, and EHR integration
     */
    post: operations["structured_diagnosis_structured_diagnosis_post"];
  };
  "/test_structured_diagnosis": {
    /**
     * Test Structured Diagnosis
     * @description Simplified test endpoint for structured diagnosis
     */
    post: operations["test_structured_diagnosis_test_structured_diagnosis_post"];
  };
  "/v1/api/case": {
    /** Create Case */
    post: operations["create_case_v1_api_case_post"];
  };
  "/v1/api/case/voice": {
    /**
     * Create Voice Case
     * @description Create a case for voice-only transcription (no image)
     */
    post: operations["create_voice_case_v1_api_case_voice_post"];
  };
  "/v1/api/case/{case_id}/finalize": {
    /**
     * Finalize Case
     * @description Deep advisory report over the full conversation once a live case ends.
     */
    post: operations["finalize_case_v1_api_case__case_id__finalize_post"];
  };
  "/v1/api/case/{case_id}/transcribe": {
    /** Transcribe Step */
    post: operations["transcribe_step_v1_api_case__case_id__transcribe_post"];
  };
  "/v1/auth/login": {
    /**
     * Auth Login
     * @description Exchange credentials for a bearer token (required in clinical mode).
     */
    post: operations["auth_login_v1_auth_login_post"];
  };
  "/v1/auth/ws-ticket": {
    /**
     * Auth Ws Ticket
     * @description Mint a short-lived WS-scoped ticket for the authenticated session.
     * WebSocket URLs carry this instead of the session JWT so proxy access
     * logs never see a long-lived credential.
     */
    post: operations["auth_ws_ticket_v1_auth_ws_ticket_post"];
  };
  "/v1/ehr/export_clinical_summary": {
    /**
     * Export Clinical Summary
     * @description Export clinical summary back to EHR system (mockup for Epic/Cerner integration)
     */
    post: operations["export_clinical_summary_v1_ehr_export_clinical_summary_post"];
  };
  "/v1/ehr/import_patient_data": {
    /**
     * Import Patient Data
     * @description Import patient data from EHR system (mockup for Epic/Cerner integration)
     */
    post: operations["import_patient_data_v1_ehr_import_patient_data_post"];
  };
  "/v1/ehr/patients": {
    /**
     * List Ehr Patients
     * @description List all available EHR patients
     */
    get: operations["list_ehr_patients_v1_ehr_patients_get"];
  };
  "/v1/ehr/patients/{patient_id}": {
    /**
     * Get Ehr Patient
     * @description Get specific EHR patient data
     */
    get: operations["get_ehr_patient_v1_ehr_patients__patient_id__get"];
  };
  "/v1/health": {
    /** Health */
    get: operations["health_v1_health_get"];
  };
  "/v1/image_infer": {
    /**
     * Image Infer
     * @description Image-only flow, returns image findings.
     */
    post: operations["image_infer_v1_image_infer_post"];
  };
  "/v1/infer": {
    /**
     * Infer
     * @description Conversation-only flow (no image).
     */
    post: operations["infer_v1_infer_post"];
  };
  "/v1/infer_from_image_only": {
    /**
     * Infer From Image Only
     * @description Image-only flow that tries to bind EHR:
     * 1) match by filename → EHR
     * 2) else match by top predicted label → first EHR with same chexpert_label
     */
    post: operations["infer_from_image_only_v1_infer_from_image_only_post"];
  };
  "/v1/knowledge_base/mode": {
    /**
     * Get Knowledge Base Mode
     * @description Facts about the loaded knowledge base.
     */
    get: operations["get_knowledge_base_mode_v1_knowledge_base_mode_get"];
    /**
     * Set Knowledge Base Mode
     * @description Kept for API compatibility: there is a single local store, so the
     * requested mode is echoed but the facts are the same.
     */
    post: operations["set_knowledge_base_mode_v1_knowledge_base_mode_post"];
  };
  "/v1/metrics": {
    /** Metrics Endpoint */
    get: operations["metrics_endpoint_v1_metrics_get"];
  };
  "/v1/multimodal_infer": {
    /**
     * Multimodal Infer
     * @description Full flow:
     * - Conversation (payload.utterances)
     * - Optional patient_id hint
     * - Optional image upload
     * - Fuse image + text + EHR
     * - RAG advisory + live questions when low confidence
     */
    post: operations["multimodal_infer_v1_multimodal_infer_post"];
  };
  "/v1/multimodal_voice_infer": {
    /**
     * Multimodal Voice Infer
     * @description Full multimodal inference with voice + image:
     * - Transcribe audio conversation
     * - Analyze uploaded image (optional)
     * - Fuse voice + image + EHR
     * - RAG advisory + live questions when low confidence
     */
    post: operations["multimodal_voice_infer_v1_multimodal_voice_infer_post"];
  };
  "/v1/quick_analysis": {
    /**
     * Quick Analysis
     * @description Return only potential issues with scores (top-k fused candidates).
     * Accepts optional utterances + optional image; fuses and returns a compact list.
     */
    post: operations["quick_analysis_v1_quick_analysis_post"];
  };
  "/v1/reload_ehr": {
    /**
     * Reload Ehr
     * @description Reload EHR JSON without restarting the server (optional convenience).
     */
    post: operations["reload_ehr_v1_reload_ehr_post"];
  };
  "/v1/reload_retriever": {
    /**
     * Reload Retriever
     * @description Re-initialize the RAG store after a KB rebuild (init is otherwise
     * once-per-process). Re-warms on a background thread.
     */
    post: operations["reload_retriever_v1_reload_retriever_post"];
  };
  "/v1/structured_diagnosis": {
    /**
     * Structured Diagnosis
     * @description Enhanced structured differential diagnosis with risk factors, red flags, and EHR integration
     */
    post: operations["structured_diagnosis_v1_structured_diagnosis_post"];
  };
  "/v1/test_structured_diagnosis": {
    /**
     * Test Structured Diagnosis
     * @description Simplified test endpoint for structured diagnosis
     */
    post: operations["test_structured_diagnosis_v1_test_structured_diagnosis_post"];
  };
  "/v1/voice_infer": {
    /**
     * Voice Infer
     * @description Voice-based inference: Transcribe audio and run through full clinical pipeline
     */
    post: operations["voice_infer_v1_voice_infer_post"];
  };
  "/v1/voice_transcribe": {
    /**
     * Voice Transcribe
     * @description Transcribe audio file using WhisperX and return formatted conversation data
     */
    post: operations["voice_transcribe_v1_voice_transcribe_post"];
  };
  "/voice_infer": {
    /**
     * Voice Infer
     * @description Voice-based inference: Transcribe audio and run through full clinical pipeline
     */
    post: operations["voice_infer_voice_infer_post"];
  };
  "/voice_transcribe": {
    /**
     * Voice Transcribe
     * @description Transcribe audio file using WhisperX and return formatted conversation data
     */
    post: operations["voice_transcribe_voice_transcribe_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_auth_login_auth_login_post */
    Body_auth_login_auth_login_post: {
      /** Password */
      password: string;
      /** Username */
      username: string;
    };
    /** Body_auth_login_v1_auth_login_post */
    Body_auth_login_v1_auth_login_post: {
      /** Password */
      password: string;
      /** Username */
      username: string;
    };
    /** Body_create_case_api_case_post */
    Body_create_case_api_case_post: {
      /** File */
      file?: string;
    };
    /** Body_create_case_v1_api_case_post */
    Body_create_case_v1_api_case_post: {
      /** File */
      file?: string;
    };
    /** Body_export_clinical_summary_ehr_export_clinical_summary_post */
    Body_export_clinical_summary_ehr_export_clinical_summary_post: {
      /** Diagnosis Result */
      diagnosis_result: string;
      /** Patient Id */
      patient_id: string;
    };
    /** Body_export_clinical_summary_v1_ehr_export_clinical_summary_post */
    Body_export_clinical_summary_v1_ehr_export_clinical_summary_post: {
      /** Diagnosis Result */
      diagnosis_result: string;
      /** Patient Id */
      patient_id: string;
    };
    /** Body_image_infer_image_infer_post */
    Body_image_infer_image_infer_post: {
      /** File */
      file: string;
    };
    /** Body_image_infer_v1_image_infer_post */
    Body_image_infer_v1_image_infer_post: {
      /** File */
      file: string;
    };
    /** Body_import_patient_data_ehr_import_patient_data_post */
    Body_import_patient_data_ehr_import_patient_data_post: {
      /** Patient Id */
      patient_id: string;
      /** Payload */
      payload: string;
    };
    /** Body_import_patient_data_v1_ehr_import_patient_data_post */
    Body_import_patient_data_v1_ehr_import_patient_data_post: {
      /** Patient Id */
      patient_id: string;
      /** Payload */
      payload: string;
    };
    /** Body_infer_from_image_only_infer_from_image_only_post */
    Body_infer_from_image_only_infer_from_image_only_post: {
      /** File */
      file: string;
    };
    /** Body_infer_from_image_only_v1_infer_from_image_only_post */
    Body_infer_from_image_only_v1_infer_from_image_only_post: {
      /** File */
      file: string;
    };
    /** Body_multimodal_infer_multimodal_infer_post */
    Body_multimodal_infer_multimodal_infer_post: {
      /** File */
      file?: string;
      /** Payload */
      payload: string;
    };
    /** Body_multimodal_infer_v1_multimodal_infer_post */
    Body_multimodal_infer_v1_multimodal_infer_post: {
      /** File */
      file?: string;
      /** Payload */
      payload: string;
    };
    /** Body_multimodal_voice_infer_multimodal_voice_infer_post */
    Body_multimodal_voice_infer_multimodal_voice_infer_post: {
      /** Audio File */
      audio_file: string;
      /** Image File */
      image_file?: string;
    };
    /** Body_multimodal_voice_infer_v1_multimodal_voice_infer_post */
    Body_multimodal_voice_infer_v1_multimodal_voice_infer_post: {
      /** Audio File */
      audio_file: string;
      /** Image File */
      image_file?: string;
    };
    /** Body_quick_analysis_quick_analysis_post */
    Body_quick_analysis_quick_analysis_post: {
      /** File */
      file?: string;
      /** Payload */
      payload?: string;
    };
    /** Body_quick_analysis_v1_quick_analysis_post */
    Body_quick_analysis_v1_quick_analysis_post: {
      /** File */
      file?: string;
      /** Payload */
      payload?: string;
    };
    /** Body_set_knowledge_base_mode_knowledge_base_mode_post */
    Body_set_knowledge_base_mode_knowledge_base_mode_post: {
      /** Mode */
      mode: string;
    };
    /** Body_set_knowledge_base_mode_v1_knowledge_base_mode_post */
    Body_set_knowledge_base_mode_v1_knowledge_base_mode_post: {
      /** Mode */
      mode: string;
    };
    /** Body_structured_diagnosis_structured_diagnosis_post */
    Body_structured_diagnosis_structured_diagnosis_post: {
      /** File */
      file?: string;
      /** Payload */
      payload: string;
    };
    /** Body_structured_diagnosis_v1_structured_diagnosis_post */
    Body_structured_diagnosis_v1_structured_diagnosis_post: {
      /** File */
      file?: string;
      /** Payload */
      payload: string;
    };
    /** Body_test_structured_diagnosis_test_structured_diagnosis_post */
    Body_test_structured_diagnosis_test_structured_diagnosis_post: {
      /** Payload */
      payload: string;
    };
    /** Body_test_structured_diagnosis_v1_test_structured_diagnosis_post */
    Body_test_structured_diagnosis_v1_test_structured_diagnosis_post: {
      /** Payload */
      payload: string;
    };
    /** Body_voice_infer_v1_voice_infer_post */
    Body_voice_infer_v1_voice_infer_post: {
      /** File */
      file: string;
    };
    /** Body_voice_infer_voice_infer_post */
    Body_voice_infer_voice_infer_post: {
      /** File */
      file: string;
    };
    /** Body_voice_transcribe_v1_voice_transcribe_post */
    Body_voice_transcribe_v1_voice_transcribe_post: {
      /** File */
      file: string;
    };
    /** Body_voice_transcribe_voice_transcribe_post */
    Body_voice_transcribe_voice_transcribe_post: {
      /** File */
      file: string;
    };
    /**
     * CaseCreateResponse
     * @description Case creation returns the compact live HUD (live=1) or the full
     * fusion payload; only case_id is invariant across both shapes.
     */
    CaseCreateResponse: {
      /** Case Id */
      case_id: string;
      [key: string]: unknown;
    };
    /** ConversationEntry */
    ConversationEntry: {
      /** Description */
      description: string;
      /** Utterances */
      utterances: components["schemas"]["Utterance"][];
    };
    /** EHRDemographics */
    EHRDemographics: {
      /** Age */
      age?: number | null;
      /** Sex */
      sex?: string | null;
    };
    /** EHRPatientDetailResponse */
    EHRPatientDetailResponse: {
      /** Patient */
      patient: {
        [key: string]: unknown;
      };
    };
    /** EHRPatientSummary */
    EHRPatientSummary: {
      /**
       * Allergies
       * @default []
       */
      allergies?: string[];
      demographics: components["schemas"]["EHRDemographics"];
      /**
       * Meds
       * @default []
       */
      meds?: string[];
      /** Patient Id */
      patient_id?: string | null;
      /**
       * Pmh
       * @default []
       */
      pmh?: string[];
      /** Vital Signs */
      vital_signs?: {
        [key: string]: unknown;
      } | null;
    };
    /** EHRPatientsResponse */
    EHRPatientsResponse: {
      /** Data Source */
      data_source: string;
      /** Patients */
      patients: components["schemas"]["EHRPatientSummary"][];
      /** Total */
      total: number;
    };
    /** FinalizeCaseResponse */
    FinalizeCaseResponse: {
      /** Case Id */
      case_id: string;
      /** Disclaimer */
      disclaimer: string;
      fusion: components["schemas"]["FusionSummary"];
      /** Model */
      model?: string | null;
      /** Report */
      report: string;
    };
    /** FusionSummary */
    FusionSummary: {
      /** Margin */
      margin: number;
      /** Top10 */
      top10: {
          [key: string]: unknown;
        }[];
      /** Top Confidence */
      top_confidence: number;
      [key: string]: unknown;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** App Mode */
      app_mode: string;
      /** Case Store */
      case_store: string;
      /** Collection */
      collection: string;
      /** Doc Count */
      doc_count?: number | null;
      /** Ehr Loaded */
      ehr_loaded: number;
      /** Ehr Synthetic */
      ehr_synthetic: boolean;
      /** Emb Model */
      emb_model: string;
      /** Image Model Loaded */
      image_model_loaded: boolean;
      llm: components["schemas"]["LLMStatus"];
      /** Persist Dir */
      persist_dir: string;
      /** Status */
      status: string;
      /** Top K */
      top_k: number;
      voice_transcription: components["schemas"]["VoiceModelsStatus"];
    };
    /** InferRequest */
    InferRequest: {
      /** Patient Id */
      patient_id?: string | null;
      /** Utterances */
      utterances: string[];
    };
    /** KnowledgeBaseModeResponse */
    KnowledgeBaseModeResponse: {
      /** Built At */
      built_at?: string | null;
      /** Description */
      description: string;
      /** Doc Count */
      doc_count?: number | null;
      /** Emb Model */
      emb_model?: string | null;
      /** Last Updated */
      last_updated?: string | null;
      /** Mode */
      mode: string;
      /** Sources */
      sources: string[];
    };
    /** LLMStatus */
    LLMStatus: {
      /** Anthropic */
      anthropic: boolean;
      /** Gemini */
      gemini: boolean;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In Minutes */
      expires_in_minutes: number;
      /** Role */
      role: string;
      /** Token Type */
      token_type: string;
    };
    /** ReloadEhrResponse */
    ReloadEhrResponse: {
      /** Ehr Loaded */
      ehr_loaded: number;
      /** Ehr Source */
      ehr_source: string;
    };
    /** ReloadRetrieverResponse */
    ReloadRetrieverResponse: {
      /** Doc Count Before */
      doc_count_before: number;
      /** Status */
      status: string;
    };
    /** TranscribeIn */
    TranscribeIn: {
      /** Utterance */
      utterance: string;
    };
    /** TranscriptionResponse */
    TranscriptionResponse: {
      /** Conversation */
      conversation: components["schemas"]["ConversationEntry"][];
      /** Session Id */
      session_id: string;
      /** Timestamp */
      timestamp: string;
    };
    /** Utterance */
    Utterance: {
      /** Confidence */
      confidence?: number;
      /** Speaker */
      speaker: string;
      /** Text */
      text: string;
      /** Timestamp */
      timestamp?: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VoiceModelsStatus */
    VoiceModelsStatus: {
      /** Alignment Model Loaded */
      alignment_model_loaded: boolean;
      /** Diarization Model Loaded */
      diarization_model_loaded: boolean;
      /** Whisperx Model Loaded */
      whisperx_model_loaded: boolean;
    };
    /** WsTicketResponse */
    WsTicketResponse: {
      /** Expires In Seconds */
      expires_in_seconds: number;
      /** Ticket */
      ticket: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Create Case */
  create_case_api_case_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_case_api_case_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CaseCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Voice Case
   * @description Create a case for voice-only transcription (no image)
   */
  create_voice_case_api_case_voice_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CaseCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Finalize Case
   * @description Deep advisory report over the full conversation once a live case ends.
   */
  finalize_case_api_case__case_id__finalize_post: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FinalizeCaseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Transcribe Step */
  transcribe_step_api_case__case_id__transcribe_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
        min_margin?: number;
      };
      path: {
        case_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranscribeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Auth Login
   * @description Exchange credentials for a bearer token (required in clinical mode).
   */
  auth_login_auth_login_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_auth_login_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Auth Ws Ticket
   * @description Mint a short-lived WS-scoped ticket for the authenticated session.
   * WebSocket URLs carry this instead of the session JWT so proxy access
   * logs never see a long-lived credential.
   */
  auth_ws_ticket_auth_ws_ticket_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WsTicketResponse"];
        };
      };
    };
  };
  /**
   * Export Clinical Summary
   * @description Export clinical summary back to EHR system (mockup for Epic/Cerner integration)
   */
  export_clinical_summary_ehr_export_clinical_summary_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_export_clinical_summary_ehr_export_clinical_summary_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Patient Data
   * @description Import patient data from EHR system (mockup for Epic/Cerner integration)
   */
  import_patient_data_ehr_import_patient_data_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_import_patient_data_ehr_import_patient_data_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Ehr Patients
   * @description List all available EHR patients
   */
  list_ehr_patients_ehr_patients_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EHRPatientsResponse"];
        };
      };
    };
  };
  /**
   * Get Ehr Patient
   * @description Get specific EHR patient data
   */
  get_ehr_patient_ehr_patients__patient_id__get: {
    parameters: {
      path: {
        patient_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EHRPatientDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /**
   * Image Infer
   * @description Image-only flow, returns image findings.
   */
  image_infer_image_infer_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_image_infer_image_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Infer
   * @description Conversation-only flow (no image).
   */
  infer_infer_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InferRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Infer From Image Only
   * @description Image-only flow that tries to bind EHR:
   * 1) match by filename → EHR
   * 2) else match by top predicted label → first EHR with same chexpert_label
   */
  infer_from_image_only_infer_from_image_only_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_infer_from_image_only_infer_from_image_only_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Knowledge Base Mode
   * @description Facts about the loaded knowledge base.
   */
  get_knowledge_base_mode_knowledge_base_mode_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeBaseModeResponse"];
        };
      };
    };
  };
  /**
   * Set Knowledge Base Mode
   * @description Kept for API compatibility: there is a single local store, so the
   * requested mode is echoed but the facts are the same.
   */
  set_knowledge_base_mode_knowledge_base_mode_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_set_knowledge_base_mode_knowledge_base_mode_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeBaseModeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Metrics Endpoint */
  metrics_endpoint_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Multimodal Infer
   * @description Full flow:
   * - Conversation (payload.utterances)
   * - Optional patient_id hint
   * - Optional image upload
   * - Fuse image + text + EHR
   * - RAG advisory + live questions when low confidence
   */
  multimodal_infer_multimodal_infer_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_multimodal_infer_multimodal_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Multimodal Voice Infer
   * @description Full multimodal inference with voice + image:
   * - Transcribe audio conversation
   * - Analyze uploaded image (optional)
   * - Fuse voice + image + EHR
   * - RAG advisory + live questions when low confidence
   */
  multimodal_voice_infer_multimodal_voice_infer_post: {
    parameters: {
      query?: {
        patient_id?: string | null;
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_multimodal_voice_infer_multimodal_voice_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Quick Analysis
   * @description Return only potential issues with scores (top-k fused candidates).
   * Accepts optional utterances + optional image; fuses and returns a compact list.
   */
  quick_analysis_quick_analysis_post: {
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_quick_analysis_quick_analysis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reload Ehr
   * @description Reload EHR JSON without restarting the server (optional convenience).
   */
  reload_ehr_reload_ehr_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReloadEhrResponse"];
        };
      };
    };
  };
  /**
   * Reload Retriever
   * @description Re-initialize the RAG store after a KB rebuild (init is otherwise
   * once-per-process). Re-warms on a background thread.
   */
  reload_retriever_reload_retriever_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReloadRetrieverResponse"];
        };
      };
    };
  };
  /**
   * Structured Diagnosis
   * @description Enhanced structured differential diagnosis with risk factors, red flags, and EHR integration
   */
  structured_diagnosis_structured_diagnosis_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_structured_diagnosis_structured_diagnosis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Test Structured Diagnosis
   * @description Simplified test endpoint for structured diagnosis
   */
  test_structured_diagnosis_test_structured_diagnosis_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_test_structured_diagnosis_test_structured_diagnosis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Case */
  create_case_v1_api_case_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_case_v1_api_case_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CaseCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Voice Case
   * @description Create a case for voice-only transcription (no image)
   */
  create_voice_case_v1_api_case_voice_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CaseCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Finalize Case
   * @description Deep advisory report over the full conversation once a live case ends.
   */
  finalize_case_v1_api_case__case_id__finalize_post: {
    parameters: {
      path: {
        case_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FinalizeCaseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Transcribe Step */
  transcribe_step_v1_api_case__case_id__transcribe_post: {
    parameters: {
      query?: {
        live?: boolean;
        max_candidates?: number;
        min_conf?: number;
        min_margin?: number;
      };
      path: {
        case_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranscribeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Auth Login
   * @description Exchange credentials for a bearer token (required in clinical mode).
   */
  auth_login_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_auth_login_v1_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Auth Ws Ticket
   * @description Mint a short-lived WS-scoped ticket for the authenticated session.
   * WebSocket URLs carry this instead of the session JWT so proxy access
   * logs never see a long-lived credential.
   */
  auth_ws_ticket_v1_auth_ws_ticket_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WsTicketResponse"];
        };
      };
    };
  };
  /**
   * Export Clinical Summary
   * @description Export clinical summary back to EHR system (mockup for Epic/Cerner integration)
   */
  export_clinical_summary_v1_ehr_export_clinical_summary_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_export_clinical_summary_v1_ehr_export_clinical_summary_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Patient Data
   * @description Import patient data from EHR system (mockup for Epic/Cerner integration)
   */
  import_patient_data_v1_ehr_import_patient_data_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_import_patient_data_v1_ehr_import_patient_data_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Ehr Patients
   * @description List all available EHR patients
   */
  list_ehr_patients_v1_ehr_patients_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EHRPatientsResponse"];
        };
      };
    };
  };
  /**
   * Get Ehr Patient
   * @description Get specific EHR patient data
   */
  get_ehr_patient_v1_ehr_patients__patient_id__get: {
    parameters: {
      path: {
        patient_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EHRPatientDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_v1_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /**
   * Image Infer
   * @description Image-only flow, returns image findings.
   */
  image_infer_v1_image_infer_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_image_infer_v1_image_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Infer
   * @description Conversation-only flow (no image).
   */
  infer_v1_infer_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InferRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Infer From Image Only
   * @description Image-only flow that tries to bind EHR:
   * 1) match by filename → EHR
   * 2) else match by top predicted label → first EHR with same chexpert_label
   */
  infer_from_image_only_v1_infer_from_image_only_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_infer_from_image_only_v1_infer_from_image_only_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Knowledge Base Mode
   * @description Facts about the loaded knowledge base.
   */
  get_knowledge_base_mode_v1_knowledge_base_mode_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeBaseModeResponse"];
        };
      };
    };
  };
  /**
   * Set Knowledge Base Mode
   * @description Kept for API compatibility: there is a single local store, so the
   * requested mode is echoed but the facts are the same.
   */
  set_knowledge_base_mode_v1_knowledge_base_mode_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_set_knowledge_base_mode_v1_knowledge_base_mode_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["KnowledgeBaseModeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Metrics Endpoint */
  metrics_endpoint_v1_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Multimodal Infer
   * @description Full flow:
   * - Conversation (payload.utterances)
   * - Optional patient_id hint
   * - Optional image upload
   * - Fuse image + text + EHR
   * - RAG advisory + live questions when low confidence
   */
  multimodal_infer_v1_multimodal_infer_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_multimodal_infer_v1_multimodal_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Multimodal Voice Infer
   * @description Full multimodal inference with voice + image:
   * - Transcribe audio conversation
   * - Analyze uploaded image (optional)
   * - Fuse voice + image + EHR
   * - RAG advisory + live questions when low confidence
   */
  multimodal_voice_infer_v1_multimodal_voice_infer_post: {
    parameters: {
      query?: {
        patient_id?: string | null;
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_multimodal_voice_infer_v1_multimodal_voice_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Quick Analysis
   * @description Return only potential issues with scores (top-k fused candidates).
   * Accepts optional utterances + optional image; fuses and returns a compact list.
   */
  quick_analysis_v1_quick_analysis_post: {
    requestBody?: {
      content: {
        "multipart/form-data": components["schemas"]["Body_quick_analysis_v1_quick_analysis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reload Ehr
   * @description Reload EHR JSON without restarting the server (optional convenience).
   */
  reload_ehr_v1_reload_ehr_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReloadEhrResponse"];
        };
      };
    };
  };
  /**
   * Reload Retriever
   * @description Re-initialize the RAG store after a KB rebuild (init is otherwise
   * once-per-process). Re-warms on a background thread.
   */
  reload_retriever_v1_reload_retriever_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReloadRetrieverResponse"];
        };
      };
    };
  };
  /**
   * Structured Diagnosis
   * @description Enhanced structured differential diagnosis with risk factors, red flags, and EHR integration
   */
  structured_diagnosis_v1_structured_diagnosis_post: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_structured_diagnosis_v1_structured_diagnosis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Test Structured Diagnosis
   * @description Simplified test endpoint for structured diagnosis
   */
  test_structured_diagnosis_v1_test_structured_diagnosis_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_test_structured_diagnosis_v1_test_structured_diagnosis_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Voice Infer
   * @description Voice-based inference: Transcribe audio and run through full clinical pipeline
   */
  voice_infer_v1_voice_infer_post: {
    parameters: {
      query?: {
        patient_id?: string | null;
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_voice_infer_v1_voice_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Voice Transcribe
   * @description Transcribe audio file using WhisperX and return formatted conversation data
   */
  voice_transcribe_v1_voice_transcribe_post: {
    parameters: {
      query?: {
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_voice_transcribe_v1_voice_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TranscriptionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Voice Infer
   * @description Voice-based inference: Transcribe audio and run through full clinical pipeline
   */
  voice_infer_voice_infer_post: {
    parameters: {
      query?: {
        patient_id?: string | null;
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_voice_infer_voice_infer_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Voice Transcribe
   * @description Transcribe audio file using WhisperX and return formatted conversation data
   */
  voice_transcribe_voice_transcribe_post: {
    parameters: {
      query?: {
        description?: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_voice_transcribe_voice_transcribe_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TranscriptionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
